# Generated by Django 5.2 on 2025-04-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminous_clinic', '0002_alter_doctorprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='selected_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luminous_clinic.service'),
        ),
    ]
