# Generated by Django 4.2.5 on 2025-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminous_clinic', '0003_remove_doctorprofile_selected_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='populate_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
